### ISSUE TITLE
Teleport Scrap Not Working

### ISSUE THREAD

**Issue by YouAnoSF** [mykooo/lethal-menu#1]
Using the function updates the position of the object but returns it to its original position, and then remains in the player's place but cannot be grabbed.

**Comment by jezbud** [comment]
Its a leeched menu. Get the official one here
https://www.unknowncheats.me/forum/other-fps-games/615575-lethal-menu-lethal-company-cheat.html

**Comment by YouAnoSF** [comment]
There I solved it, adding
grabbable Object.start Falling Position = player.transform.position + Vector3.up * 0.25f; (so that the scrap does not go back to the beginning)
and
grabbableObject.EnablePhysics(true); (and for the scrap to be grabbed)


`PlayerControllerB player = selectedPlayer;
                        foreach (GrabbableObject grabbableObject in UnityEngine.Object.FindObjectsByType<GrabbableObject>(FindObjectsSortMode.None))
                        {
                            if (!grabbableObject.isHeld && !grabbableObject.isPocketed && !grabbableObject.isInShipRoom)
                            {
                                grabbableObject.transform.position = player.transform.position + Vector3.up * 0.25f;
                                grabbableObject.startFallingPosition = player.transform.position + Vector3.up * 0.25f;
                                grabbableObject.EnablePhysics(true);
                                grabbableObject.FallToGround();
                                grabbableObject.Update();
                            }
                        }`

**Comment by jezbud** [comment]
Its fixed in the newest official release anyway
