### ISSUE TITLE
COPIED MENU

### ISSUE THREAD

**Issue by jezbud** [mykooo/lethal-menu#2]
Nice copied Menus.

First is Project Apparatus
2nd is Lethal Menu by ice

**Comment by mykooo** [comment]
Yes, it is the menu from IcyRelic I just want to provide an open source version for the people who want it.

**Comment by IcyRelic** [comment]
its not your menu to post an open source version. You didnt even credit me. You took my name out of the menu and slapped your own in there. You also have german text in there. 90% of the people using my menu probably read english
